name: Java CI with Gradle + build docker

env:
  CONTEXT_DIR: './'

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle build
      run: ./gradlew build

    - name: Execute Gradle Cucumber
      run: ./gradlew cucumber
